version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Lisbon"
    reviewers: ["rubemlrm"]
    open-pull-requests-limit: 99
    commit-message:
      prefix: "build: "
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Europe/Lisbon"
    reviewers: ["rubemlrm"]
    commit-message:
      prefix: "build: "
